apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
]

belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    #url(r'^', include('apps.wishlist.urls', namespace='wishlist')),
    url(r'^admin/', admin.site.urls),
    url(r'^wishlist/', include('apps.wishlist.urls', namespace='wishlist'))
]

apps/login/models.py
#####################################################
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re
from datetime import datetime
################### email regex #################################
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
############# name regex ############################################
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')
##############################################################   
class UserManager(models.Manager):
    def validate_and_register(self, postData):
        errors = {}
       ##############   NAME   ###############################
        if not len(postData['name']):
            errors['name'] = "field is empty."
        elif len(postData['name']) < 2:
            errors['name'] = "Name too short."
        #########   Alias ###################################
        if not len(postData['alias']):
            errors['alias'] = "field is empty."
        elif len(postData['alias']) < 2:
            errors['alias'] = "Alias too short."
        ############### email validations #####################
        if not len(postData['userName']):
            errors['userName'] = "field is empty."
        elif len(postData['alias']) < 2:
            errors['userName'] = "UserName too short."
        #################### email validations ##################
        if not len(postData['email']):
            errors['email'] = "Email field can not be empty."
        elif not re.match(EMAIL_REGEX, postData['email']):
            errors['email'] = "Invalid email! Please input the right format of an email like: user@mail.com"
        ###################  password ######################
        if not len(postData['password']):
            errors['password'] = "Password field can not be empty."
        elif len(postData['password']) < 8:
            errors['password'] = "Password too short. Input at least 8 characters"
        elif postData['password'] != postData['confirm_pass']:
            errors['confirm_pass'] = "Password not confirmed. Please pay more attention"
        ###################### birthday and date #################
        if not postData['datehired']:
            errors['datehired'] = "field is empty"
        else:
            now = datetime.today().date()
            #birthday = datetime.strptime(postData['birthday'], "%A %d. %B %Y").date()
            datehired = datetime.strptime(postData['datehired'], "%Y-%m-%d").date()
           
        if len(errors):
            return (False, errors)
        else:
            password = postData['password'].encode()
            hashed = bcrypt.hashpw(password, bcrypt.gensalt())
            self.create(name = postData['name'], alias = postData['alias'], email = postData['email'], password = hashed, datehired = datehired)
            ####################
            new_user = self.create(
                name=postData['name'],
                alias=postData['alias'],
                email=postData['email'],
                password=hashed,
                datehired=postData['datehired']
            )
            #print new_user
            return (True,new_user)
            

    def validate_and_login(self, postData):
        errors_login = {}
        # Email Validation when Login
        if not len(postData['email']):
            errors_login['login_email_error'] = "Please provide an email."
        else:
            if not self.filter(email = postData['email']):
                errors_login['login_error'] = "wrong email or passwd."
        
        if not len(errors_login):
            user = self.filter(email = postData['email'])
        # Password Validation when Login
            if not len(postData['password']):
                errors_login['login_password_error'] = "Please type your email password."
            else:
                password = postData['password'].encode()
                hashed = self.filter(email = postData['email'])[0].password.encode()
                if not bcrypt.checkpw(password, hashed):
                    errors_login['login_error'] = "wrong email or passwd"

        if len(errors_login):
            return (False, errors_login)
        else:
            return (True, self.filter(email = postData['email']))
      
        if len(errors_login):
            return (False, errors_login)
        else:
            return (True, self.filter(email = postData['email']))
              
####################  Model ######################################
class User(models.Model):
    name = models.CharField(max_length = 255)
    alias = models.CharField(max_length = 45)
    email = models.CharField(max_length = 255)
    userName = models.CharField(max_length=48)
    password = models.CharField(max_length = 255)
    datehired = models.DateField(max_length = 45)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect
from .models import User
#from ..models import User
from django.contrib import messages
##################################
def index(request):
    return render(request, "login/index.html")

##################################
def register(request):
    result = User.objects.validate_and_register(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "login/index.html", context)
    if result[0] == True:
        context = {
            'name': result[1],
        }
        return render(request, "login/index.html", context)
###############################################################
def login(request):
    result = User.objects.validate_and_login(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "login/index.html", context)
    if result[0] == True:

        request.session['user_name'] = result[1][0].name
        request.session['user_id'] = result[1][0].id

        return redirect('wishlist:index')
    

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login and Registeration</title>
</head>

<body>
  <fieldset>
    <table>
    <legend><h3>Login</h3></legend>

    {% for message in messages %}
    <h3 id="error">{{message}}</h3>
    {% endfor %}

    <form action="{% url 'login:login' %}" method="post">
      {% csrf_token %}
      <tr>
        <td>
          <label for="email">Email:</label>
        </td>
        <td>
          <input type="text" name="email">
        </td>
        <td id="error">{{result.login_email_error}}</td>
      </tr>
      <tr>
        <td>
          <label for="password">Password:</label>
        </td>
        <td>
          <input type="password" name="password">
        </td>
        <td id="error">{{result.login_password_error}}</td>
      </tr>

      <br>
      <p id="error">{{result.login_error}}</p>
      <br>
      <input type="submit" value="Login">
    </form>
    <br>
    <h3 id="success">{{name}} {{action}}</h3>
    </table>
  </fieldset>
  
  <fieldset>
    <table>
    <legend><h3>Registeration</h3></legend>
    <form action="{% url 'login:register' %}" method="post">
      {% csrf_token %}
      <tr>
        <td>
          <label for="name">Name:</label>
        </td>
        <td>
          <input type="text" name="name">
        </td>
        <td id="error">{{result.name}}</td>
      </tr>
      
      <tr>
        <td>
          <label for="alias">alias:</label>
        </td>
        <td>
          <input type="text" name="alias">
        </td>
        <td id="error">{{result.alias}}</td>
      </tr>
      
      <tr>
        <td>
          <label for="datehired">Datehired:</label>
        </td>
        <td>
          <input type="date" name="datehired">
        </td>
        <td id="error">{{result.datehired}}</td>
      </tr>
      
      <tr>
        <td>
          <label for="userName">User Name:</label>
        </td>
        <td>
          <input type="text" name="userName">
        </td>
        <td id="error">{{result.userName}}</td>
      </tr>
      <tr>
        <td>
          <label for="email">Email:</label>
        </td>
        <td>
          <input type="email" name="email">
        </td>
        <td id="error">{{result.email}}</td>
      </tr>
      <tr>
        <td>
          <label for="password">Password:</label>
        </td>
        <td>
          <input type="password" name="password">
        </td>
        <td id="error">{{result.password}}</td>
      </tr>
      
      <tr>
        <td>
          <label for="confirm_pass">Password Confirmation</label>
        </td>
        <td>
          <input type="password" name="confirm_pass">
        </td>
        <td id="error">{{result.confirm_pass}}</td>
      </tr>
      <input type="submit" value="Please Register">
    </form>
    </table>
  </fieldset>
</body>

</html>