apps/wishlist/urls.py
from django.conf.urls import url
from . import views
#from django import models
#####################################
urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^logout$', views.logout, name = "logout"),
    url(r'^create_item$', views.create_item, name='create_item'),
    url(r'^leave/(?P<item_id>\d+)', views.leave, name="leave"),
    url(r'^join/(?P<item_id>\d+)', views.join, name="leave"),
    url(r'^info/(?P<item_id>\d+)', views.info, name="leave")
    
]

belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    #url(r'^', include('apps.wishlist.urls', namespace='wishlist')),
    url(r'^admin/', admin.site.urls),
    url(r'^wishlist/', include('apps.wishlist.urls', namespace='wishlist'))
]

apps/wishlist/models.py
# Create your models here.
from __future__ import unicode_literals
from django.db.models import Count
from django.db import models
from ..login.models import User
######################################################

class ProductManager(models.Manager):
    def addProduct(self, postData, user_id):
        errors = []
        response = {}
        if len("".join(postData['productName'].split())) < 3:
            errors.append("Please give your product a name at least 3 characters long.")
            response['status']=False
            response['errors']=errors
        else:
            response['status']=True
            user = User.objects.get(id=user_id)
            newProduct=Wishlist.objects.create(name=postData['productName'], created_by=user)
            newProduct.wished_by.add(user)
            newProduct.save()
            response['product']=newProduct
        return response

##########################################################
class Wishlist(models.Model):
    name = models.CharField(max_length=255)
    created_by=models.ForeignKey(User,related_name='created_prodcut',null=True)
    wished_by=models.ManyToManyField(User,related_name='wished_prodcut',null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects = ProductManager()

apps/wishlist/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from ..login.models import User
from .models import *
from django.core.urlresolvers import reverse
#from django.db.models import Count
######################################
def index(request):
    if not 'user_name' in request.session:
        messages.add_message(request, messages.INFO, "Please Login")
        return redirect('login:index')
        #return render(request, "wishlist:index.html", context)
    me = User.objects.get(id = request.session['user_id'])
    context = {
        'me' : me,
        'my_items' : Wishlist.objects.filter(wished_by=me),
        'other_items' : Wishlist.objects.exclude(wished_by=me)
    }
    return render(request, "wishlist/index.html", context)

def logout(request):
    request.session.flush()
    return redirect('login:index')

#def Dashboard(request):


def create_item(request):
    result = Wishlist.objects.addProduct(request.POST, request.session['user_id'])
    if result['status']:
        return redirect('wishlist:index')
    return redirect('/')

def wishlist(request):
    if request.method == 'POST':
        add.objects.my_list(request.POST)
        return redirect('wishlist:index')

def leave(request, item_id):
    user = User.objects.get(id=request.session['user_id'])
    item = Wishlist.objects.get(id=item_id)
    item.wished_by.remove(user)
    item.save()
    return redirect('/wishlist/')


def join(request, item_id):
    user = User.objects.get(id=request.session['user_id'])
    item = Wishlist.objects.get(id=item_id)
    item.wished_by.add(user)
    item.save()
    return redirect('/wishlist/')

def info(request, item_id):
    context = {
    'item' : Wishlist.objects.get(id=item_id)
    }
    return render(request, 'wishlist/info.html', context)

apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Registration</title>
</head>

<body>
    <fieldset>
        <a href="{% url 'wishlist:logout' %}">Logout</a>
        <h3>{{request.session.user_name}}</h3>
        <h3>{{request.session.user_email}}</h3>
        <h3>{{request.session.user_id}}</h3>
    </fieldset>
    <fieldset>
        <legend>My wish list</legend>
            <table>
               <thead>
                   <tr>
                       <th>Creator: </th>
                       <th>Item :</th>
                       <th>Action:</th>
                   </tr>
               </thead> 
               <tbody>
                   {% for item in my_items %}
                   <tr>
                       <td>{{item.created_by.name}}</td>
                       <td><a href="/wishlist/info/{{item.id}}">{{item.name}}</a></td>
                       <td><a href="/wishlist/leave/{{item.id}}">Leave</a></td>
                   </tr>
                   {% endfor %}
               </tbody>
            </table>
    </fieldset>
    <h3>Participants & wishlist:</h3>
    <h3>Hello, {{request.session.userName}}</h3>
    
     <fieldset>
        <legend>Other wish lists</legend>
            <table>
               <thead>
                   <tr>
                       <th>Creator: </th>
                       <th>Item :</th>
                       <th>Action:</th>
                   </tr>
               </thead> 
               <tbody>
                   {% for item in other_items %}
                   <tr>
                       <td>{{item.created_by.name}}</td>
                       <td><a href="/wishlist/info/{{item.id}}">{{item.name}}</a></td>
                       <td><a href="/wishlist/join/{{item.id}}">Join</a></td>
                   </tr>
                   {% endfor %}
               </tbody>
            </table>
    </fieldset>

    <fieldset>
        <h3>Create a new wishlist item!</h3>
       <form action='/wishlist/create_item' method='post' >
            {% csrf_token %} Item / Product:
            <input type="text" name="productName" value="">
            <input type="submit" name="" value="Add">
        </form>
    </fieldset>
    <fieldset>
        <p>wishlist items:</p>
        {%for user in product.created_by.all%}
        <p>{{user.name}}</p>
        {%endfor%}
    </fieldset>
</table>
</body>
</html>

apps/wishlist/templates/wishlist/info.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<h1>Info page for : {{item.name}}</h1>
	<h3>List of everyone that likes this item:</h3>
	<ul>
		{% for user in item.wished_by.all %}
		<li>{{user.name}}</li>
		{% endfor %}
	</ul>

</body>
</html>